#!/bin/bash

echo "exit - Salir del chat
/up - Subir una página
/down - Bajar una página
/top - Ir al principio
/bottom - Ir al final
/lines - Mostrar el número de línea de cada mensaje
/react [n] [emoji] - Reaccionar con un emoji al mensaje en la línea n
/[r|g|c|p][mensaje] - Cambia el color del mensaje
//[mensaje] - Cambia el color del texto al color original
/help - Muestra este mensaje de ayuda"
