#!/bin/bash

function chat_help() {
    echo "Uso: ./main <chat> [name]"
    echo "Ejemplo: chat.sh chat1 john"
}

function parse_yaml() {
    local prefix=$2
    local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
    sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
    awk -F$fs '{
        indent = length($1)/2;
        vname[indent] = $2;
        for (i in vname) {if (i > indent) {delete vname[i]}}
        if (length($3) > 0) {
            vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
            printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
        }
    }'
}

function update() {
    git pull
}

function file_setup() {
    # If file $path exists
    if [ -f $chat_file ]; then
        # If the first line is #/bin/chat, then read it
        if [ "$(head -n 1 $chat_file)" != "#/bin/chat $chat" ]; then
            # If the first line is not #/bin/chat, then show error
            echo "Error: The file $chat_file exists and it isn't a chat. For security meassures it won't be open or edited." 1>&2
            echo "If you think the file should be open, try running \"sed -i 's/\r$//' $chat_file\" to remove Windows trash from the file" 1>&2
            exit 1
        fi
    else
        # If the file does not exist, then create it
        echo "Setting up chat $chat"
        install -D /dev/null $chat_file
        echo "#/bin/chat $chat" > $chat_file
    fi
}

function layout() {
    session="$chat-as-$name"

    tmux has-session -t $session 2>/dev/null
    if [ $? -ne 0 ]; then
        ./layout $session $chat_file $name $color $display_size $display_lines
    fi

    tmux attach-session -t $session
}

chat="$1"
if [ -z "$chat" ] || [ "$chat" = "--help" ]; then
    chat_help
    exit 1
fi

eval $(parse_yaml settings.yml "settings_")

if [ "$chat" = "--update" ] || [ "$settings_updates_auto" = "true" ]; then
    update
    if [ "$chat" = "--update" ]; then
        exit 0
    fi
fi

chat_file="./$chat.yml"
if [ -n "settings_chat_path" ]; then
    chat_file="$settings_chat_path/$chat.yml"
fi

name="$2"
if [ -z "$name" ]; then
    if [ -n "$settings_name_username" ]; then
        name="$settings_name_username"
    else
        name="$(whoami)"
    fi
fi

# Replace the spaces with _
chat="${chat// /_}"
name="${name// /_}"

color="$settings_name_color"
if [ -z "$color" ]; then
    color="/c"
fi

display_size=0
if [ -n "$settings_display_size" ]; then
    display_size="$settings_display_size"
fi

display_lines=0
if [ "$settings_display_numbers" = "true" ]; then
    display_lines=1
fi

file_setup

layout
